import { describe, expect, it, vi } from 'vitest'
import { TaskTitleDraft } from '../src/features/task-control/task-title-draft.js'

it('does not reject or silently normalize an unchanged legacy empty or whitespace title', async () => {
  const save = vi.fn(async () => {})
  for (const title of ['', '  ']) {
    const controller = new TaskTitleDraft(title, save)
    expect(await controller.flush()).toBe(true)
    expect(controller.snapshot().draft).toBe(title)
  }
  expect(save).not.toHaveBeenCalled()
})

function deferred() {
  let resolve!: (value: unknown) => void
  let reject!: (cause: Error) => void
  const promise = new Promise<unknown>((accept, fail) => { resolve = accept; reject = fail })
  return { promise, resolve, reject }
}

describe('タスク名の保存と画面移動', () => {
  it('入力中の保存を flush が待ち、失敗しても下書きとエラーを保持する', async () => {
    const pending = deferred()
    const save = vi.fn(() => pending.promise)
    const draft = new TaskTitleDraft('元の名前', save)
    draft.focus(true)
    draft.update('変更した名前')
    void draft.save()
    draft.focus(false)
    let completed = false
    const flushing = draft.flush().then((ok) => { completed = true; return ok })
    await Promise.resolve()
    expect(completed).toBe(false)
    expect(draft.snapshot().flushing).toBe(true)
    draft.update('移動中の別入力')
    expect(draft.snapshot().draft).toBe('変更した名前')
    pending.reject(new Error('保存先に書き込めない'))
    expect(await flushing).toBe(false)
    draft.receive('元の名前')
    expect(draft.snapshot()).toMatchObject({ draft: '変更した名前', error: '保存先に書き込めない', saving: false, flushing: false })
    expect(save.mock.calls).toEqual([['変更した名前', '元の名前']])
  })
  it('保存中に追加した文字も、成功した直前の名前を期待値にして保存する', async () => {
    const pending = deferred()
    const save = vi.fn().mockReturnValueOnce(pending.promise).mockResolvedValue(true)
    const draft = new TaskTitleDraft('元の名前', save)
    draft.update('途中')
    const saving = draft.save()
    draft.update('さらに追加した名前')
    draft.receive('途中')
    expect(draft.snapshot().draft).toBe('さらに追加した名前')
    pending.resolve(true)
    expect(await saving).toBe(true)
    expect(save.mock.calls).toEqual([['途中', '元の名前'], ['さらに追加した名前', '途中']])
    expect(await draft.flush()).toBe(true)
    expect(save).toHaveBeenCalledTimes(2)
  })
  it('false を返した保存も失敗として扱い、同じ入力で再試行できる', async () => {
    const save = vi.fn().mockResolvedValueOnce(false).mockResolvedValue(true)
    const draft = new TaskTitleDraft('元の名前', save)
    draft.update('下書き')
    expect(await draft.flush()).toBe(false)
    expect(draft.snapshot().draft).toBe('下書き')
    expect(await draft.flush()).toBe(true)
    expect(save.mock.calls).toEqual([['下書き', '元の名前'], ['下書き', '元の名前']])
    expect(draft.snapshot().error).toBe('')
  })
  it('空欄への変更は保存済みの名前に戻し、前後の空白だけは保存時に除く', async () => {
    const save = vi.fn().mockResolvedValue(true)
    const draft = new TaskTitleDraft('元の名前', save)
    draft.update('   ')
    expect(await draft.flush()).toBe(true)
    expect(draft.snapshot()).toMatchObject({ draft: '元の名前', error: '' })
    expect(save).not.toHaveBeenCalled()
    draft.update('  新しい名前  ')
    expect(await draft.flush()).toBe(true)
    expect(save.mock.calls).toEqual([['新しい名前', '元の名前']])
    expect(draft.snapshot().draft).toBe('新しい名前')
  })
  it('保存待ち中の空欄も完了した保存内容へ戻り、画面移動を妨げない', async () => {
    const pending = deferred()
    const draft = new TaskTitleDraft('元の名前', async () => pending.promise)
    draft.update('保存する名前')
    const saving = draft.save()
    draft.update(' ')
    const closing = draft.flush()
    pending.resolve(true)
    expect(await saving).toBe(true)
    expect(await closing).toBe(true)
    expect(draft.snapshot()).toMatchObject({ draft: '保存する名前', error: '' })
  })
  it('同じ名前の外部編集は両方を残して停止し、明示再保存だけを許可する', async () => {
    const save = vi.fn().mockResolvedValue(true)
    const draft = new TaskTitleDraft('元の名前', save)
    draft.update('自分の名前')
    draft.receive('外部で保存した名前')
    expect(draft.snapshot()).toMatchObject({ draft: '自分の名前', conflict: '外部で保存した名前' })
    expect(await draft.flush()).toBe(false)
    expect(save).not.toHaveBeenCalled()
    expect(await draft.retry()).toBe(true)
    expect(save.mock.calls).toEqual([['自分の名前', '外部で保存した名前']])
    expect(draft.snapshot().conflict).toBeNull()
  })
  it('自分の返答が遅れても新しい外部保存の起点を戻さず、最新を採用できる', async () => {
    const pending = deferred()
    const save = vi.fn().mockReturnValueOnce(pending.promise).mockResolvedValue(true)
    const draft = new TaskTitleDraft('元の名前', save)
    draft.update('自分の保存')
    const saving = draft.save()
    draft.receive('自分の保存')
    expect(draft.snapshot().conflict).toBeNull()
    draft.receive('さらに新しい外部保存')
    pending.resolve(true)
    expect(await saving).toBe(false)
    expect(draft.snapshot()).toMatchObject({ draft: '自分の保存', conflict: 'さらに新しい外部保存' })
    expect(await draft.acceptLatest()).toBe(true)
    draft.update('次の入力')
    expect(await draft.flush()).toBe(true)
    expect(save.mock.calls).toEqual([['自分の保存', '元の名前'], ['次の入力', 'さらに新しい外部保存']])
  })
  it('フォーカスだけでは古い名前を保存せず、未編集の外部変更を取り込む', async () => {
    const save = vi.fn().mockResolvedValue(true)
    const draft = new TaskTitleDraft('元の名前', save)
    draft.focus(true)
    draft.receive('外部で更新')
    expect(draft.snapshot().draft).toBe('外部で更新')
    expect(await draft.flush()).toBe(true)
    expect(save).not.toHaveBeenCalled()
  })
})
